pusher:
  jwt:
    cookieName: PUSHER_TOKEN
    secret: sing@Login(Auth}*^31)&wemihu% # 登录校验的密钥
    pubKeyPath: rsa.pub # 公钥地址
    priKeyPath: rsa.pri # 私钥地址
    expire: 20160 # 过期时间,单位分钟
    cookieMaxAge: 20160
  filter:
    allowPaths:
      - /user/accredit*
      - /user/register*
      - /test/*
#      - /**

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/pusher?serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: s12ss12s
    hikari:
      idle-timeout: 60000
      maximum-pool-size: 30
      minimum-idle: 10
  jackson:
    default-property-inclusion: non_null
mybatis:
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    xyz.humilr.pusherserver.dao: DEBUG
server:
#  port: 8080